### PR TITLE
Don't crash in stopWork if registerIdleTransitionCallback hasn't been called yet

### LINKED ISSUE #20: IdlingRegistry doesn't set registerIdleTransitionCallback until a IdlingResourceRegistry sync
io.reactivex.rxjava2:rxandroid:2.1.0
io.reactivex.rxjava2:rxjava:2.2.2
com.squareup.rx.idler:rx2-idler:0.9.1
androidx.test.espresso:espresso-core:3.2.0
androidx.test.espresso:espresso-idling-resource:3.2.0

I have an application that injects our ScheduleProviders, so in our test app component I was having to use the `RxIdler.wrap()` functionality and I am registering them as IdlingResources in a custom ActivityTestRule before the `base?.evaluate()`. 

Since `Espresso.registerIdlingResources()` is now a deprecated function, I was using the `IdlingRegistry.getInstance().register()`. However I have a couple of tests that have no UI interactions that were crashing for null pointer exceptions on the `DelegatingIdlingResourceSchedulers.stopWork()` for a null ResourceCallback. Even though I could debug through and see the Schedulers in the list of registered resources in the IdlingRegistry. This didn't happen if I changed the call to use the deprecated `Espresso.registerIdlingResources()`.
After much debugging I discovered that this is because:
`Espresso.registerIdlingResources()` immediately causes a sync on the IdlingResourceRegistry which is where the registerIdleTransitionCallback() happens. Whereas the IdlingRegistry does not sync with the IdlingResourceRegistry until an IdleNotifier is necessary. 
I am able to force this by calling an Espresso interaction immediately after registering.  

All of my tests now work the same by exchanging 
```
@Suppress("DEPRECATION")
Espresso.registerIdlingResources(scheduler)
```
with 
```
IdlingRegistry.getInstance().register(scheduler)
Espresso.onIdle()
```

I thought this information might help a few other people, or could be an addition to the README for how to fully register these IdlingResources with the newer IdlingRegistry.

### PR DESCRIPTION
**Pull request by technoir42**
Fixes #20

### CODE REVIEW

**Comment by technoir42** [comment]
@jrodbx can you take a look please

**Comment by startthread** [comment]
Can we please merge this PR? getting crash otherwise.

**Comment by jdulaney** [comment]
this PR fixed the issue for me; would be great to be merged in

**Comment by JaimeToca** [comment]
@technoir42 Fixed the issue for me too. It would be nice if this can be merged ...

**Comment by jameswald** [comment]
Does anyone know why `registerIdleTransitionCallback(ResourceCallback)` isn't being called before `stopWork()`? Or perhaps it is being called, but with a `null` argument?

**Comment by technoir42** [comment]
@jameswald if you install `DelegatingIdlingResourceScheduler` but don't use Espresso in an instrumented test or run the app itself without instrumentation, `stopWork` will be called but `registerIdleTransitionCallback` and you'll get NPE.

**Comment by Silencegod** [comment]
Please merge this PR

**Comment by Lounah** [comment]
PLEASE MERGE THIS ONE

**Comment by Barboskin** [comment]
Пацаны, давайте замержим уже please

**Comment by technoir42** [comment]
@jrodbx is anyone still maintaining this library?

**Comment by odlund** [comment]
Just another comment asking to get this fix merged.

**Comment by jrodbx** [comment]
Debugged the underlying issue with @gamepro65 (thanks to @MerryMaryMaguire's detailed notes) and looks like this fix works, thanks for the contribution!

I filed https://github.com/android/android-test/issues/650 to raise awareness on the behavior change, in case of an unexpected regression in Espresso.

**Pull request merged**
